[theme]
primaryColor = "#4CAF50"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 20

[browser]
gatherUsageStats = false

[deprecation]
showfileUploaderEncoding = false

[global]
disableWatchdogWarning = true
showWarningOnDirectExecution = false 